"""Adiciona status ao emprestimo (em_dia/atrasado)

Revision ID: 955daef57d44
Revises: 4afe38899bae
Create Date: 2026-09-04 00:30:16.706264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955daef57d44'
down_revision = '4afe38899bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprestimos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('em_dia', 'atrasado', name='status_emprestimo'), server_default='em_dia', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emprestimos', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
